- name: Install base packages
  import_tasks: packages.yml

- name: Configure system user
  import_tasks: users.yml

- name: Setup filesystem
  import_tasks: filesystem.yml

- name: Setup AWS utilities
  import_tasks: aws.yml