# =====================================================
# Environment
# =====================================================

environment: prod

# =====================================================
# AWS Resources
# =====================================================

s3_bucket_name: ridelist-media-prod

# =====================================================
# Secrets/Params Manager Configuration
# =====================================================
ridelist_required_secrets:
  - database
  - jwt

ridelist_optional_secrets:
  - smtp
  - aws

ridelist_required_parameters:
  - app-config
  - ecr-images
  - infrastructure/aws-region
  - s3-bucket-name


# =====================================================
# Domain Names
# =====================================================

domain_name: ridelist.com.ng

api_domain_name: api.ridelist.com.ng