---
- name: Discover storage device
  import_tasks: discover.yml

- name: Prepare filesystem
  import_tasks: filesystem.yml

- name: Mount storage
  import_tasks: mount.yml

- name: Create application directories
  import_tasks: directories.yml

- name: Validate storage setup
  import_tasks: validate.yml