from aws_cdk import (
    Stack,
    aws_secretsmanager as secretsmanager,
    SecretValue as secret_value,
)
from constructs import Construct

from .utils.utilities import formulate_resource_id
from .utils.config_constants import Constants


class SecretsStack(Stack):

    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        **kwargs,
    ):
        super().__init__(scope, construct_id, **kwargs)

        env = self.node.try_get_context(
            Constants.DEPLOYMENT_ENVIRONMENT_KEY
        )

        # -----------------------------------
        # DATABASE SECRET
        # Shell only — values injected via
        # GitHub Actions at deploy time
        # -----------------------------------
        self.db_secret = secretsmanager.Secret(
            self,
            formulate_resource_id(self, "DatabaseSecret"),
            secret_name=f"/ridelist/{env}/database",
            description=f"RideList database credentials for {env}",
        )

        # -----------------------------------
        # JWT SECRET
        # JWT_SECRET auto-generated by AWS;
        # expiry constants baked in at creation
        # -----------------------------------
        self.jwt_secret = secretsmanager.Secret(
            self,
            formulate_resource_id(self, "JwtSecret"),
            secret_name=f"/ridelist/{env}/jwt",
            description=f"RideList JWT config for {env}",
            generate_secret_string=secretsmanager.SecretStringGenerator(
                secret_string_template=(
                    '{"JWT_EXPIRATION":"86400000",'
                    '"JWT_REFRESH_EXPIRATION":"604800000"}'
                ),
                generate_string_key="JWT_SECRET",
                exclude_punctuation=True,
                password_length=64,
            ),
        )

        # -----------------------------------
        # AWS CONFIG
        # Access keys omitted — use IAM roles
        # -----------------------------------
        self.aws_secret = secretsmanager.Secret(
            self,
            formulate_resource_id(self, "AwsSecret"),
            secret_name=f"/ridelist/{env}/aws",
            description=f"RideList AWS config for {env}",
            secret_object_value={
                "AWS_REGION": secret_value.unsafe_plain_text(
                    "eu-west-1"
                ),
                "AWS_S3_BUCKET": secret_value.unsafe_plain_text(
                    f"ridelist-media-{env}"
                ),
            },
        )

        # -----------------------------------
        # APP CONFIG
        # Non-sensitive defaults only;
        # SMTP credentials injected via
        # GitHub Actions at deploy time
        # -----------------------------------
        self.app_secret = secretsmanager.Secret(
            self,
            formulate_resource_id(self, "AppSecret"),
            secret_name=f"/ridelist/{env}/app",
            description=f"RideList app config for {env}",
            secret_object_value={
                "EMAIL_SENDER": secret_value.unsafe_plain_text("mock"),
                "EMAIL_FROM": secret_value.unsafe_plain_text(
                    "noreply@ofspain.click"
                ),
                "EMAIL_FROM_NAME": secret_value.unsafe_plain_text(
                    "RideList"
                ),
                "SMTP_HOST": secret_value.unsafe_plain_text(
                    "smtp.gmail.com"
                ),
                "SMTP_PORT": secret_value.unsafe_plain_text("587"),
                "SMTP_USERNAME": secret_value.unsafe_plain_text(""),
                "SMTP_PASSWORD": secret_value.unsafe_plain_text(""),
                "FRONTEND_BASE_URL": secret_value.unsafe_plain_text(
                    "https://ofspain.click"
                ),
                "IMAGE_MIN_COUNT": secret_value.unsafe_plain_text("1"),
                "IMAGE_MAX_COUNT": secret_value.unsafe_plain_text("10"),
                "IMAGE_MAX_SIZE_MB": secret_value.unsafe_plain_text("5"),
            },
        )
